name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Buildozer and Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev git unzip openjdk-11-jdk zlib1g-dev libncurses5 libstdc++6 libffi-dev libssl-dev liblzma-dev libjpeg-dev libpng-dev
        sudo apt install -y android-sdk  # تثبيت SDK Android
        sudo apt install -y android-tools-adb android-tools-fastboot  # تثبيت أدوات adb و fastboot
        sudo apt install -y build-essential  # تثبيت الأدوات الأساسية للبناء
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-APK
        path: bin/*.apk
